version: '3'
services:
    apache2:
      build: .
      volumes:
        - "./src/:/usr/local/apache2/htdocs/:Z"
      container_name: homepage
      restart: always
      ports:
          - 8080:80

networks:
  default:
    external:
      name: npm-network

